# Generated by Django 3.0 on 2020-09-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privileges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prvtype',
            name='description',
            field=models.CharField(default='nie wprowadzono opisu', max_length=1000),
        ),
        migrations.AddField(
            model_name='prvtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
